package bai7_Abstract_class_and_interface.thuc_hanh.lop_animal_and_interface_edible.fruit;
import bai7_Abstract_class_and_interface.thuc_hanh.lop_animal_and_interface_edible.edible.Edible;
public abstract class Fruit implements Edible {
}